//! A [Riemann](http://riemann.io/) client library and command line interface.

extern crate libc;
extern crate protobuf;

/// Layer one: Protobuf implementation generated by `protoc --rust_out`.
pub mod proto;
pub mod transport;
pub mod client;
pub mod error;

pub use self::client::{Client};
pub use self::error::{Error, Result};
